[package]
name = "colab-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
anyhow.workspace = true
axum.workspace = true
colab-server-domain = { path = "../domain" }
colab-server-auth = { path = "../auth" }
colab-server-persistence = { path = "../persistence" }
colab-server-email = { path = "../email" }
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
tower-http.workspace = true
uuid.workspace = true
sha2.workspace = true
hex.workspace = true
base64.workspace = true
colab-observability = { path = "../../../../observability/rust" }

percent-encoding = "2.3"
object_store = { version = "0.14.2", features = ["aws"] }
zstd = "0.13.3"
async-compression = { version = "0.4", features = ["tokio", "zstd"] }

chrono = "0.4"
