import {resource,core,eventually} from './client.mjs';import {openTab} from './gui.mjs';
export async function invoke(ctx,{gui=false,query='Reply with REGRESSION_OK. Do not change files or contact anyone.'}={}){
 const a=resource(ctx,'agent'),c=resource(ctx,'channel');const unique=query+' '+ctx.runId+' '+crypto.randomUUID();
 let message;
 if(gui){await openTab(ctx,'Messages');const editor=ctx.page.getByLabel('Message '+c.name,{exact:true});await editor.fill('');await editor.pressSequentially('@'+a.name.split(' ')[0]);await ctx.page.locator('form').getByRole('button').filter({has:ctx.page.getByText(a.name,{exact:true})}).click();await editor.press('End');await editor.pressSequentially(' '+unique);await ctx.page.getByRole('button',{name:'Send message',exact:true}).click();const rows=await eventually(ctx,'GUI message is durably committed',()=>core(ctx,'GET','/v1/channels/'+c.id+'/messages?after=0&limit=200'),rows=>rows.some(m=>m.body.includes(unique)));message=rows.find(m=>m.body.includes(unique));}
 else message=await core(ctx,'POST','/v1/channels/'+c.id+'/messages',{plainText:'@'+a.name+' '+unique,content:{type:'doc',content:[{type:'paragraph',content:[{type:'mention',attrs:{kind:'agent',id:a.id,label:a.name}},{type:'text',text:' '+unique}]}]},clientNonce:crypto.randomUUID()});
 const requests=await eventually(ctx,'Mention creates the intended Agent request',()=>core(ctx,'GET','/v1/channels/'+c.id+'/agent-requests'),rows=>rows.some(r=>r.triggerMessageId===message.id&&r.targetBlueprintId===a.id));const request=requests.find(r=>r.triggerMessageId===message.id&&r.targetBlueprintId===a.id);
 return {message,request,agent:a,channel:c};
}
export async function complete(ctx,task){const rows=await eventually(ctx,'Real Agent completes execution',()=>core(ctx,'GET','/v1/channels/'+task.channel.id+'/agent-requests'),rows=>rows.some(r=>r.id===task.request.id&&['succeeded','failed'].includes(r.state)),{timeoutMs:180000});const request=rows.find(r=>r.id===task.request.id);ctx.assert('Real runtime execution completed successfully',request.state,'succeeded');const replies=await eventually(ctx,'Agent sends a real result reply',()=>core(ctx,'GET','/v1/channels/'+task.channel.id+'/messages?after='+task.message.seq+'&limit=200'),rows=>rows.some(r=>r.senderBlueprintId===task.agent.id&&r.replyToMessageId===(Object.hasOwn(task,'replyToMessageId')?task.replyToMessageId:task.request.triggerMessageId||null)&&r.body.includes('REGRESSION_OK')),{timeoutMs:20000});ctx.assert('Result has the expected blueprint identity',replies.some(r=>r.senderBlueprintId===task.agent.id&&r.replyToMessageId===(Object.hasOwn(task,'replyToMessageId')?task.replyToMessageId:task.request.triggerMessageId||null)&&r.body.includes('REGRESSION_OK')),true);return request;}
export async function actualPrompt(ctx,request){const work=await eventually(ctx,'Provider work events are persisted',()=>core(ctx,'GET','/v1/agent-requests/'+request.id+'/events',undefined,{capture:false}),v=>v.events.some(e=>e.params?.threadId),{timeoutMs:20000});const thread=work.events.find(e=>e.params?.threadId)?.params.threadId;if(!thread)ctx.block('Runtime input cannot be resolved: no provider thread ID');const response=await ctx.command('Read the test request runtime input','python3',['regression_test/support/prompt.py',thread],{capture:false});ctx.assert('Runtime input reader succeeds',response.code,0);const input=JSON.parse(response.stdout);if(!input.found)ctx.block('The real runtime Session is not accessible on this test machine');const matching=input.inputs.filter(t=>t.includes(request.id));ctx.assert('One assembled input identifies this request',matching.length,1);return matching[0];}
