export const USECASE={name:'Paste, resize and consume Canvas images',description:'Upload a real image through GUI and R2, verify reload and Markdown handle, set hidden Agent interpretation, download exact original bytes and preserve the image across text edits. Archive only the owned document.'};
export const META={id:'canvas.editing.images',module:'canvas/editing',surface:'gui',priority:'critical',origin:'requirement',status:'trial',effects:'isolated-write',cost:'normal',requires:['local-core'],affectedPaths:['desktop/ui/src/features/canvas','local/canvas-codec','server/standalone/crates/api/src/canvas_images.rs'],suite:'business',testLevel:'end-to-end',locks:['read:client.primary','read:channel.shared','write:canvas.collection']};
export const REQUIREMENTS={channel:{permission:'read'},parameters:{keys:['disposable']}};
import {createDocument,deleteDocument} from '../../../support/canvas.mjs';
import {core,eventually,disposable,data,cli} from '../../../support/client.mjs';
import {openTab} from '../../../support/gui.mjs';
import {createHash} from 'node:crypto';
import {readFile,unlink} from 'node:fs/promises';
import path from 'node:path';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAKAAAABkCAIAAACO1KzYAAABY0lEQVR4nO3OAQkAMQDEsEqbtEl7aa+iHIxCBIR7vjyM+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+iYj6IivkgKuaDqJgPomI+iIr5ICrmg6iYD6JiPoiK+SAq5oOomA+i+gHH0MV0C3tF5QAAAABJRU5ErkJggg==','base64');
export async function run(ctx){disposable(ctx);const doc=await createDocument(ctx);const output=path.join('/tmp','colab-canvas-image-'+ctx.runId+'.png');try{
 const editor=ctx.page.locator('[contenteditable=true]').first();await editor.fill('Image context before');
 await ctx.page.route('**/v1/canvases/'+doc.id+'/images',route=>route.fulfill({status:503,body:'Temporary upload failure'}));
 await ctx.page.locator('input[type=file][accept*="image/png"]').setInputFiles({name:'canvas-regression.png',mimeType:'image/png',buffer:png});
 await ctx.page.getByRole('button',{name:'Retry',exact:true}).waitFor();
 ctx.assert('Failed uploads never insert a broken image',await editor.locator('img').count(),0);
 await ctx.page.unroute('**/v1/canvases/'+doc.id+'/images');await ctx.page.getByRole('button',{name:'Retry',exact:true}).click();
 const image=editor.locator('img[data-canvas-image]').first();await image.waitFor({timeout:30000});
 await eventually(ctx,'Uploaded image loads',()=>image.evaluate(el=>el.complete&&el.naturalWidth>0),Boolean); 
 const id=await image.getAttribute('data-canvas-image');
 await image.hover();const handle=editor.locator('[data-resize-handle="bottom-right"]').first();const box=await handle.boundingBox();ctx.assert('Resize handle is visible',Boolean(box&&box.width>0),true);
 await ctx.page.mouse.move(box.x+box.width/2,box.y+box.height/2);await ctx.page.mouse.down();await ctx.page.mouse.move(box.x+box.width/2+80,box.y+box.height/2+50,{steps:8});await ctx.page.mouse.up();
 await eventually(ctx,'Resize geometry is durable',()=>core(ctx,'GET','/v1/canvases/'+doc.id+'/document'),v=>{const m=v.content.match(/colab-image:[0-9a-f-]+ \"([^\"]+)\"/);return m&&JSON.parse(Buffer.from(m[1],'base64url')).width>160;});
 const projection=await eventually(ctx,'Image handle is durable in projection',()=>core(ctx,'GET','/v1/canvases/'+doc.id+'/document'),v=>v.content.includes('colab-image:'+id));
 ctx.assert('Projection never embeds binary image bytes',projection.content.includes('data:image'),false);
 const interpretation='One pixel test fixture '+ctx.runId;
 await core(ctx,'PATCH','/v1/canvas-images/'+id,{image_interpretation:interpretation});
 await ctx.page.reload();await openTab(ctx,'Canvas');await ctx.page.locator(`[data-item-id="${doc.id}"]`).click();await image.waitFor();
 ctx.assert('Hidden interpretation is absent from GUI',await editor.innerText().then(text=>text.includes(interpretation)),false);
 const result=data(await cli(ctx,'colab-canvas',['image-read','--id',id,'--output',output]));
 ctx.assert('Agent receives hidden interpretation',result.imageInterpretation,interpretation);
 ctx.assert('Agent downloads original bytes',createHash('sha256').update(await readFile(output)).digest('hex'),createHash('sha256').update(png).digest('hex'));
 await editor.press('ControlOrMeta+End');
 await editor.evaluate((el,bytes)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'pasted.png',{type:'image/png'}));el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));},[...png]);
 await eventually(ctx,'Pasted image inserts through upload',()=>editor.locator('img[data-canvas-image]').count(),count=>count===2);
 await editor.evaluate((el,bytes)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'dropped.png',{type:'image/png'}));const box=el.getBoundingClientRect();el.dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,clientX:box.left+30,clientY:box.top+30,bubbles:true,cancelable:true}));},[...png]);
 await eventually(ctx,'Dropped image inserts through upload',()=>editor.locator('img[data-canvas-image]').count(),count=>count===3);
 const before=await core(ctx,'GET','/v1/canvases/'+doc.id+'/document');
 await core(ctx,'POST','/v1/canvases/'+doc.id+'/apply-patch',{patch:'*** Begin Patch\n*** Update File: document.md\n@@\n-Image context before\n+Image context updated\n*** End Patch'});
 const after=await core(ctx,'GET','/v1/canvases/'+doc.id+'/document');
 ctx.assert('Text patch preserves every image handle',after.content.match(/colab-image:[0-9a-f-]+/g),before.content.match(/colab-image:[0-9a-f-]+/g));
 await ctx.screenshot('Canvas image loaded and resized after reload');
 }finally{await unlink(output).catch(()=>{});await deleteDocument(ctx,doc);}}
