[package]
name = "colab-server-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
yrs = "0.28.0"
anyhow.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
thiserror.workspace = true
ring = "0.17.14"
base64.workspace = true

pulldown-cmark = "0.13"
serde_yaml = "0.9"

[dev-dependencies]
tokio.workspace = true
